config/routes.rb
Rails.application.routes.draw do
  get 'cookie_clicker/index'
  devise_for :models
  root "tweets#index"
    resources :models, only: [:show] do
      resources :relationships, only: [:create, :show]
    end
    resources :relationships, only: [:destroy]
    resources :tweets do
      resources :comments
    end
    resources :cookie_clickers
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :model
  validates :comment, presence: true
end

app/models/cookie_clicker.rb
class CookieClicker < ApplicationRecord
  belongs_to :model
  validates :click_count, presence: true 
end

app/models/model.rb
class Model < ApplicationRecord
  has_many :tweets
  has_many :comments
  has_one :cookie_clicker
  has_many :following, foreign_key: "follower_id", class_name: "Relationship"
  has_many :followers, foreign_key: "followed_id", class_name: "Relationship"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates_uniqueness_of :username
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "Model"
    belongs_to :followed, class_name: "Model"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :model
    has_many :comments, dependent: :destroy

    validates :body, presence: true
    validates :mood, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if:  :devise_controller?


    protected

        def configure_permitted_parameters

            devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @tweet = Tweet.find(params[:tweet_id])
        @comment = Tweet.comments.new
    end
    
    def show
    end

    def create
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.create(comment_params)
        if @comment.save
            redirect_to tweet_path(@tweet)
        end
    end 

    def edit
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.find(params[:id])
    end 

    def update
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.find(params[:id])
        if @comment.save(comment_params)
            redirect_to tweet_path(@tweet)
        else
            render :new
        end

    end

    def destroy
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.find(params[:id])
        @comment.destroy
        redirect_to root_path
        
    end

    private
    def comment_params
        params.require(:comment).permit(:comment, :commenter, :model_id)
    end
end

app/controllers/cookie_clickers_controller.rb
class CookieClickersController < ApplicationController
  def index
    @cookie_clicker = CookieClicker.new
  end

  def show
    @cookie_clicker = CookieClicker.find(params[:id])
  end

  def new
    @cookie_clicker = CookieClicker.new(click_count: 0)
  end

  def create
    @cookie_clicker = CookieClicker.new(clicker_params)
    @cookie_clicker.save
    redirect_to @cookie_clicker
  end

  def edit
    @cookie_clicker = CookieClicker.find(params[:id])
  end

  def update
    @cookie_clicker = CookieClicker.find(params[:id])
    @cookie_clicker.update(clicker_params)
    redirect_to @cookie_clicker
  end

  private
    def clicker_params
      params.require(:cookie_clicker).permit(:click_count,:model_id)
    end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
    def show
        @model = Model.find(params[:id])
        @rel = @model.followers.find_by(follower: current_model)
      end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
        @model = Model.find(params[:model_id])
        @rel = Relationship.new(follower_id: current_model.id, followed_id: @model.id)
        @rel.save
        redirect_to model_path(@model)
    end

    def show
        @model = Model.find(params[:model_id])
    end

    def destroy
        @rel = Relationship.find(params[:id])
        @rel.destroy
        redirect_to model_path(@rel.followed_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_model!
    def index
        @tweets = Tweet.all.order("created_at DESC")
        @tweet = Tweet.new
    end

    def show
        @tweet = Tweet.find(params[:id])
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Tweet.new(tweet_params)
        if @tweet.save
            redirect_to root_path
        else
            render "new"
        end
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        @tweet = Tweet.find(params[:id])
        if @tweet.update(tweet_params)   
            redirect_to root_path
        else
            render :new
        end
    end

    def destroy
        @tweet = Tweet.find(params[:id])
        @tweet.destroy
        redirect_to root_path
    end

    private
        def tweet_params
            params.require(:tweet).permit(:body,:mood,:model_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookie_clicker_helper.rb
module CookieClickerHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= link_to "@" + comment.commenter, model_path(comment.model_id) %></strong>
  <%= comment.comment %>
  <% if comment.model_id == current_model.id %>
    <%= link_to "Delete", [comment.tweet, comment], method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-link btn-sm" %>
  <% end %>
</p>

app/views/comments/_form.html.erb
 <%= form_with model: [@tweet, @tweet.comments.build] do |form| %>
        <div class="row">
            <div class="col">
                <div class="field form-group">
                    <%= form.text_area :comment, class:"form-control"%>
                </div>
            </div>
            <div class="col">
                <div>
                    <%= form.number_field :model_id, id: :comment_model_id, value: current_model.id, type: :hidden%>
                </div>
            </div>
        </div>
        <div>
            <%= form.text_field :commenter, value: current_model.username, type: :hidden%>
        </div>
        <div class="actions">
            <div class="row">
                <%= form.submit class:"btn btn-sm btn-outline-primary mr-3 ml-3"%>
                <%= link_to "Done", root_path, class:"btn btn-sm btn-outline-primary"%>
        </div>
<% end %>

app/views/cookie_clickers/_clicker.html.erb
<h1> SPACE </h1>
<div class='card p-3' >
<%= form_with model: @cookie_clicker do |form| %>
        <div class="field form-group">
          <%= form.number_field :click_count, value: @cookie_clicker.click_count + 1, class:"form-control"%>
        </div>
        <div>
          <%= form.number_field :model_id, value: current_model.id, type: :hidden %>
        </div>
        <div class="actions">
          <%= form.submit 'MORE COOKIES', class:"btn btn-outline-primary" %>
        </div>
<% end %> 
</div> 

app/views/cookie_clickers/edit.html.erb
<%= render 'clicker'%>

app/views/cookie_clickers/index.html.erb
<h1>CookieClicker#index</h1>
<p>Find me in app/views/cookie_clicker/index.html.erb</p>
<% if current_model.cookie_clicker == 0%>
    <%= link_to "Start New Cookie Adventure", new_cookie_clicker_path, class:'btn btn-outline-primary'%>
<% else %>
    <%= link_to "Load in Cookie Adventure", cookie_clicker_path(current_model.cookie_clicker), class:'btn btn-outline-primary'%>
<% end %>

app/views/cookie_clickers/new.html.erb
<%= render 'clicker'%>

Cookies<%=  @cookie_clicker.click_count%>

app/views/cookie_clickers/show.html.erb
<%= render 'clicker'%>

Cook<%= @cookie_clicker.click_count%>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Twitter</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="w-auto">
    <%= render "tweets/header"%>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
    </div>
    <%= yield %>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/models/placeholder.html.erb
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-8">
            <div class="card mt-5 border-primary">
            <div class="card-header">
                <h2>Profile</h2>
            </div>
                <div class="card-body">
                    <div class="row p-3">
                        <div class="col">
                            <div class ="row">
                            <h4 class="card-title p-2"><%= @model.username %></h4> 
                            </div>
                            
                        </div>
                        <div class="col">
                            <div class="card mb-3" style="max-width: 18rem;">
                                
                                <div class="card-body">
                                    <h5 class="card-title">Info card title</h5>
                                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                            </div>
                            <h5> Followers: <%= @model.followers.count%> |  Following: <%= @model.following.count%></h5>
                            <%= link_to "Show Followers", model_relationship_path(@model.id)%>
                            

                        </div>
                    </div>
                    <p class="card-text"><%= @model.email%></p>
                    <p class="card-text"><small class="text-muted">Bio</small></p>
                    <div>
                        <% if current_model.id == @model.id%>
                            <%= link_to "Edit Profile", edit_model_registration_path, class:"btn btn-sm btn-outline-primary"%>
                        <% else %>
                            <% if @rel.present?%>
                                <%=link_to "Unfollow", relationship_path(@rel), method: :delete, class:"btn btn-sm btn-outline-primary mr-2"%>
                            <% else %>
                                <%=link_to "Follow", model_relationships_path(@model),method: :post, class:"btn btn-sm btn-outline-primary mr-2"%>
                            <% end %>
                        <% end %>
                        <%= link_to "Back", root_path, class:"btn btn-sm btn-outline-primary mr-2"%>
                    </div>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>

app/views/models/show.html.erb
<div class="container">
    <div class="col m-3">
        <div class="card border-primary">
            <div class="card-header">
                <h2>Profile</h2>
            </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h4 class="card-title">@<%= @model.username %> | Tweets: <%= @model.tweets.count %></h4>   
                            <h5><%= link_to "Followers: " + @model.followers.count.to_s, model_relationship_path(@model.id)%> |
                                <%= link_to "Following: " + @model.following.count.to_s, model_relationship_path(@model.id)%>
                            </h5>         
                        </div>
                        <div class="col">
                            <div class="card mb-3" style="max-width: 18rem;">
                                <div class="card-body">
                                        <h5 class="card-title">Info card title</h5>
                                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <p class="card-text">Email: <%= @model.email%></p>
                    <p class="card-text"><small class="text-muted">Bio</small></p>
                    <div>
                        <% if current_model.id == @model.id%>
                            <%= link_to "Edit Profile", edit_model_registration_path, class:"btn btn-sm btn-outline-primary"%>
                        <% else %>
                            <% if @rel.present?%>
                                <%=link_to "Unfollow", relationship_path(@rel), method: :delete, class:"btn btn-sm btn-outline-primary mr-2"%>
                            <% else %>
                                <%=link_to "Follow", model_relationships_path(@model),method: :post, class:"btn btn-sm btn-outline-primary mr-2"%>
                                <% end %>
                        <% end %>
                        <%= link_to "Back", root_path, class:"btn btn-sm btn-outline-primary mr-2"%>
                    </div>
                </div>    
       </div>
    <br>
    <% if @model.id == current_model.id %>
        <h3> Your Tweets </h3>
    <% else %>
        <h3> <%= @model.username%>'s Tweets </h3>
    <% end %>   
        <% @model.tweets.each do |tweet|%>
            <div class="card mt-3">
            <div class="card-header">
                <h4>@<%= @model.username%></h4>
                <%= time_ago_in_words(tweet.created_at).titleize %> Ago
            </div>
                <div class="card-body">
                <p class="card-text"><%= tweet.body %></p>
                <footer class="blockquote-footer"> Mood: 
                    <cite title="Source Title"><%= tweet.mood %></cite>
                </footer>
                <%  if tweet.model_id == current_model.id%>
                    <%= link_to "Delete Tweet", tweet_path(tweet), 
                    method: :delete, data: { confirm: "Are you sure?" },
                    class:"btn btn-outline-danger btn-sm mt-1 mb-1"%>
                <%  end %>
                <h5 class="card-text mt-3">Comments: <%= tweet.comments.count()%></h5> 
                <%= render tweet.comments%>
                <%= link_to "Add Comment", tweet, class:"btn btn-outline-primary btn-sm mt-1 mb-2"%>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/relationships/_followers.html.erb
<ul class="list-group">
    <% @model.followers.each do |follower|%>
        <li class="list-group-item">
            <%= link_to "@" + follower.follower.username , model_path(follower.follower_id)%>
        </li>
    <% end %>
</ul>   

app/views/relationships/_following.html.erb
<ul class="list-group">
    <% @model.following.each do |following|%>
        <li class="list-group-item">
            <%= link_to "@" + following.followed.username , model_path(following.followed_id)%>
        </li>
    <% end %>
</ul>

app/views/relationships/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4 m-3">
      <h1> Followers </h1>
      <%= render "relationships/followers"%>
      <%= link_to "Back", :back, class:"btn btn-sm btn-outline-primary mt-4"%>
    </div>
    <div class="col-4 m-3">
      <h1> Following </h1>
      <%= render "relationships/following"%>
    </div>
  </div>
  
</div>

app/views/tweets/_form.html.erb
<div class="container p-1">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"> Tweet</h5>

      <%= form_with model: @tweet do |form| %>
        <div class="field form-group">
          <%= form.text_area :body, class:"form-control", placeholder:"Tweet"%>
        </div>
        <div class="field form-group">
          <%= form.text_field :mood, class:"form-control", placeholder:"Mood" %>
        </div>
        <div>
          <%= form.number_field :model_id, id: :tweet_model_id, value: current_model.id, type: :hidden%>
          
        </div>
          <br>
        <div class="actions">
          <%= form.submit class:"btn btn-outline-primary" %>
        </div>
      <% end %>  

    </div>
  </div>
</div>

app/views/tweets/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#6bc0ff">
  <div class="container-fluid">
    <%= link_to "Twitter", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if model_signed_in?%>
          <li class="nav-item">
           <%= link_to "Profile", current_model, class:"navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "New Tweet", new_tweet_path, class:"navbar-brand" %>
          </li>
          <li class="nav-item">
              <%= link_to "CookieClicker", cookie_clickers_path, class:"navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_model_session_path, method: :delete, class:"navbar-brand"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_model_registration_path, class:"navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_model_session_path, class:"navbar-brand"%>
          </li>
        <% end %>

      </ul>

    </div>
  </div>
</nav>

app/views/tweets/_leftcol.html.erb
<div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
</div>

app/views/tweets/_rightcolumn.html.erb
<ul class="list-group mt-2">
  <li class="list-group-item">An item</li>
  <li class="list-group-item">A second item</li>
  <li class="list-group-item">A third item</li>
  <li class="list-group-item">A fourth item</li>
  <li class="list-group-item">And a fifth one</li>
</ul>

app/views/tweets/_tweetscolumn.html.erb
<h1> Tweets </h1>
<br>
  <%= render "form"%>
  <% @tweets.each do |tweet|%>
    <div class="card mt-3">
      <div class="card-header">
        <h4><%=link_to "@" + tweet.model.username, tweet.model%></h4>
        <%= time_ago_in_words(tweet.created_at).titleize %> Ago
      </div>
        <div class="card-body">
          <p class="card-text"><%= tweet.body %></p>
          <footer class="blockquote-footer"> Mood: 
            <cite title="Source Title"><%= tweet.mood %></cite>
          </footer>
          <%  if tweet.model_id == current_model.id%>
            <%= link_to "Edit Tweet", edit_tweet_path(tweet), class:"btn btn-outline-primary btn-sm" %>
            <%= link_to "Delete Tweet", tweet_path(tweet), 
              method: :delete, data: { confirm: "Are you sure?" },
              class:"btn btn-outline-danger btn-sm mt-1 mb-1"%>
          <%  end %>
          <h5 class="card-text mt-3">Comments: <%= tweet.comments.count()%></h5> 
          <%= render tweet.comments%>
          <%= link_to "Add Comment", tweet, class:"btn btn-outline-primary btn-sm mt-1 mb-2"%>
        </div>
    </div>
  <% end %>
<br>

app/views/tweets/edit.html.erb
<%= render "form"  %>

app/views/tweets/index.html.erb
<div class="container-fluid mr-3 ">  
  <div class="row mt-4">
    <div class="col">
      <%= render "leftcol"%>
    </div>
    <div class="col-7">
      <%= render "tweetscolumn"%>
    </div> 
    <div class="col">
      <%= render "rightcolumn"%>
    </div>
  </div>
</div>

  
  

app/views/tweets/new.html.erb
<%= render "form"%>

app/views/tweets/show.html.erb
<div class="container">
    <div class="row mt-3">
        <div class ="col-2"></div>
        <div class ="col-8">
            <h1> Showing Tweet </h1>    
            <div class="card mt-2">
            <h4><div class="card-header"><%=@tweet.model.username%></div></h4>
                <div class="card-body">
                <p class="card-text"><%= @tweet.body %></p>
                <footer class="blockquote-footer"> Mood: 
                    <cite title="Source Title"><%= @tweet.mood %></cite>
                </footer>
                <%  if @tweet.model_id == current_model.id%>
                    <%= link_to "Delete Tweet", tweet_path(@tweet), 
                        method: :delete, data: { confirm: "Are you sure?" },
                        class:"btn btn-outline-primary btn-sm mt-1 mb-1"%>
                <%  end %> 
                <h5>Comments: <%= @tweet.comments.count()%></h5> 
                <%= render @tweet.comments%>
                <%= render "comments/form"%>
                
                </div>
                
            </div>
            
        </div>
    </div>
</div>
  